name: swift-meal
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/api?schema=public
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/src/app

volumes:
  postgres_data:
