name: swift-meal
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swift-meal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686'   # UI
      - '4318:4318'     # OTLP/HTTP
      - '4317:4317'     # OTLP/gRPC
      - '14250:14250'   # gRPC Jaeger ingest
      - '14268:14268'   # Thrift ingest
      - '14269:14269'   # Prometheus
    networks:
      - swift-meal-network
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3333:3333
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/src/main.js"]
    networks:
      - swift-meal-network
    depends_on:
      database:
        condition: service_healthy
      jaeger:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.route-prefix=/'
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - swift-meal-network
    restart: unless-stopped
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - swift-meal-network
    restart: unless-stopped
    depends_on:
      - prometheus
      - jaeger

networks:
  swift-meal-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: