name: swift-meal
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686'   # UI
      - '4318:4318'     # OTLP/HTTP
      - '4317:4317'     # OTLP/gRPC
      - '14250:14250'   # gRPC Jaeger ingest
      - '14268:14268'   # Thrift ingest
# app:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   container_name: api
#   environment:
#     - DATABASE_URL=postgresql://postgres:postgres@db:5432/api?schema=public
#   ports:
#     - 3333:3333
#   volumes:
#     - .:/usr/src/app

volumes:
  postgres_data:
