name: swift-meal
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3333:3333
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/src/main.js"]
    depends_on:
      database:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686'   # UI
      - '4318:4318'     # OTLP/HTTP
      - '4317:4317'     # OTLP/gRPC
      - '14250:14250'   # gRPC Jaeger ingest
      - '14268:14268'   # Thrift ingest
      - '14269:14269'   # Prometheus

volumes:
  postgres_data: