global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'api:3333'