name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test (Unit + Integration)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit and Integration Tests
        run: npm run test

  e2e-tests:
    name: E2E Tests with PostgreSQL
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build-and-test

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: api
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready (Bash TCP Check)
        run: |
          for i in {1..10}; do
            echo "Checking if PostgreSQL is ready (attempt $i)..."
            (echo > /dev/tcp/localhost/5432) >/dev/null 2>&1 && echo "PostgreSQL is ready!" && exit 0
            sleep 2
          done
          echo "PostgreSQL did not become ready in time." && exit 1

      - name: Run E2E Tests
        run: npm run test:e2e

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: [build-and-test, e2e-tests]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials (Static Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login into the container registry
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ steps.generate_sha.outputs.sha }} .
          docker tag ${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ steps.generate_sha.outputs.sha }} ${{ secrets.AWS_ECR_REPOSITORY_URI }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ steps.generate_sha.outputs.sha }}
          docker push ${{ secrets.AWS_ECR_REPOSITORY_URI }}:latest
